version: 2.1
############
# Workflows
############
workflows:
  version: 2
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .
      - run:
          command: |
            pytest